server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml


clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: weather-loader-component-logs
          __path__: /logs/weather-loader-component/*.log
          
      - targets:
          - localhost
        labels:
          job: weather-metrics-component-logs
          __path__: /logs/weather-metrics-component/*.log 