global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'weather-loader-component'
    metrics_path: '/weather-loader-component/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
  
  - job_name: 'weather-metrics-component'
    metrics_path: '/weather-metrics-component/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
